name: Django Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            if [ ! -d "/www/wwwroot/social-network-api/.git" ]; then
                git clone https://${{ secrets.REPO_TOKEN }}@github.com/luzhnyak/social-network-api.git /www/wwwroot/social-network-api
            fi
            cd /www/wwwroot/social-network-api
            git config --global --add safe.directory /www/wwwroot/social-network-api
            git pull origin main            